import {
  Activity,
  Boxes,
  Database,
  FileText,
  Flame,
  Globe,
  HardDrive,
  KeyRound,
  Layers,
  Network,
  Package,
  Shield,
  TerminalSquare,
  User,
  Wrench,
} from "lucide-react";

export const TASK_GROUPS = [
  {
    id: "system-info",
    title: "System Info",
    icon: Activity,
    description: "Quick system identification and baseline checks.",
    tasks: [
      { id: "os-release", title: "Detect OS", tags: ["system", "info"], command: "cat /etc/os-release || uname -a" },
      { id: "uname", title: "Kernel & Arch", tags: ["system", "info"], command: "uname -a" },
      { id: "uptime", title: "Uptime & Load", tags: ["system", "info"], command: "uptime" },
      { id: "cpu", title: "CPU Info", tags: ["system", "info"], command: "lscpu || cat /proc/cpuinfo | head" },
      { id: "mem", title: "Memory Usage", tags: ["system", "info"], command: "free -h || vm_stat" },
      { id: "top", title: "Top Processes", tags: ["system", "process"], command: "ps aux --sort=-%mem | head -n 20" },
      { id: "env", title: "Env Vars (preview)", tags: ["system", "debug"], command: "env | sort | sed -n '1,80p'" },
    ],
  },
  {
    id: "packages",
    title: "Packages",
    icon: Package,
    description: "APT/YUM package management shortcuts.",
    tasks: [
      { id: "apt-update", title: "APT Update", tags: ["apt", "install"], command: "sudo apt-get update" },
      { id: "apt-upgrade", title: "APT Upgrade", tags: ["apt", "install"], command: "sudo apt-get upgrade -y" },
      { id: "apt-fix", title: "Fix Broken Packages", tags: ["apt", "repair"], command: "sudo apt-get -f install -y" },
      { id: "pkg-search", title: "Search Package (APT)", tags: ["apt", "info"], command: "apt-cache search nginx | head -n 30" },
      { id: "pkg-installed", title: "List Installed (APT)", tags: ["apt", "info"], command: "dpkg -l | sed -n '1,60p'" },
      { id: "yum-info", title: "YUM/DNF Info", tags: ["yum", "info"], command: "command -v dnf && dnf --version || yum --version || true" },
    ],
  },
  {
    id: "users-ssh",
    title: "Users & SSH",
    icon: User,
    description: "User checks and SSH daemon basics.",
    tasks: [
      { id: "whoami", title: "Who am I", tags: ["user", "info"], command: "whoami && id" },
      { id: "users", title: "Logged-in Users", tags: ["user", "info"], command: "who || w" },
      { id: "sudo-check", title: "Sudo Privileges", tags: ["user", "security"], command: "sudo -n true && echo 'sudo: yes' || echo 'sudo: no'" },
      { id: "ssh-status", title: "SSH Service Status", tags: ["ssh", "service"], command: "sudo systemctl status ssh --no-pager || sudo service ssh status || true" },
      { id: "ssh-config", title: "Show sshd_config (key lines)", tags: ["ssh", "config"], command: "sudo grep -E '^(Port|PermitRootLogin|PasswordAuthentication|PubkeyAuthentication|AllowUsers|AllowGroups)' /etc/ssh/sshd_config || true" },
      { id: "auth-log", title: "Auth Log (tail)", tags: ["ssh", "logs"], command: "sudo tail -n 80 /var/log/auth.log 2>/dev/null || sudo journalctl -u ssh -n 80 --no-pager || true" },
    ],
  },
  {
    id: "network",
    title: "Networking",
    icon: Network,
    description: "IPs, routes, DNS, and ports.",
    tasks: [
      { id: "ip-a", title: "IP Addresses", tags: ["network", "info"], command: "ip a || ifconfig" },
      { id: "routes", title: "Routes", tags: ["network", "info"], command: "ip route || netstat -rn" },
      { id: "dns", title: "DNS Resolver", tags: ["network", "info"], command: "cat /etc/resolv.conf || true" },
      { id: "ping", title: "Ping 1.1.1.1", tags: ["network", "debug"], command: "ping -c 4 1.1.1.1 || true" },
      { id: "curl-ip", title: "Public IP", tags: ["network", "info"], command: "curl -s ifconfig.me || curl -s https://api.ipify.org || true" },
      { id: "listening", title: "Listening Ports", tags: ["network", "info"], command: "sudo ss -tulpn || sudo netstat -tulpn || true" },
      { id: "firewall", title: "UFW Status", tags: ["security", "firewall"], command: "sudo ufw status verbose || true" },
    ],
  },
  {
    id: "disk-fs",
    title: "Disk & Filesystem",
    icon: HardDrive,
    description: "Disk space, mounts, and large files.",
    tasks: [
      { id: "df", title: "Disk Usage (df)", tags: ["disk", "info"], command: "df -hT" },
      { id: "du", title: "Directory Size (cwd)", tags: ["disk", "info"], command: "du -sh ./* 2>/dev/null | sort -hr | head -n 20" },
      { id: "mounts", title: "Mounts", tags: ["disk", "info"], command: "mount | sed -n '1,60p'" },
      { id: "inode", title: "Inode Usage", tags: ["disk", "info"], command: "df -ih" },
      { id: "largest", title: "Largest Files (cwd)", tags: ["disk", "cleanup"], command: "find . -maxdepth 3 -type f -printf '%s %p\\n' 2>/dev/null | sort -nr | head -n 20" },
    ],
  },
  {
    id: "services",
    title: "Services",
    icon: Wrench,
    description: "Systemd/service basics.",
    tasks: [
      { id: "systemctl-failed", title: "Failed Units", tags: ["systemd", "debug"], command: "sudo systemctl --failed --no-pager || true" },
      { id: "systemctl-list", title: "Running Services", tags: ["systemd", "info"], command: "sudo systemctl list-units --type=service --state=running --no-pager | sed -n '1,80p'" },
      { id: "journal", title: "Journal Tail", tags: ["logs", "debug"], command: "sudo journalctl -n 120 --no-pager || true" },
      { id: "dmesg", title: "dmesg (tail)", tags: ["kernel", "debug"], command: "sudo dmesg | tail -n 120 || true" },
    ],
  },
  {
    id: "service-control",
    title: "Service Control",
    icon: Wrench,
    description: "Interactive systemd runbooks (pick a service, then run actions).",
    tasks: [
      {
        id: "svc-restart",
        title: "Restart service",
        tags: ["systemd", "service"],
        requires: ["service"],
        command: "sudo systemctl restart {{service}}",
      },
      {
        id: "svc-status",
        title: "Status",
        tags: ["systemd", "service"],
        requires: ["service"],
        command: "sudo systemctl status {{service}} --no-pager",
      },
      {
        id: "svc-follow-logs",
        title: "Follow logs (stream)",
        tags: ["systemd", "logs"],
        requires: ["service"],
        longRunning: true,
        command: "sudo journalctl -u {{service}} -f --no-pager",
      },
      {
        id: "svc-last-200",
        title: "Last 200 logs",
        tags: ["systemd", "logs"],
        requires: ["service"],
        command: "sudo journalctl -u {{service}} -n 200 --no-pager",
      },
      {
        id: "svc-failed",
        title: "Failed services",
        tags: ["systemd", "debug"],
        command: "sudo systemctl --failed --no-pager || true",
      },
    ],
  },
  {
    id: "nodejs",
    title: "Node.js",
    icon: TerminalSquare,
    description: "Install/check Node, npm, and common process managers.",
    tasks: [
      {
        id: "node-install-20",
        title: "Install Node.js 20 (Ubuntu/Debian)",
        tags: ["node", "install"],
        command:
          "curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash - && sudo apt-get install -y nodejs",
      },
      { id: "node-version", title: "Node & npm version", tags: ["node", "info"], command: "node -v && npm -v" },
      { id: "corepack", title: "Enable Corepack", tags: ["node", "tools"], command: "sudo corepack enable || corepack enable" },
      { id: "pnpm", title: "Install pnpm (corepack)", tags: ["node", "tools"], command: "corepack prepare pnpm@latest --activate" },
      { id: "pm2-install", title: "Install PM2", tags: ["node", "pm2"], command: "sudo npm i -g pm2" },
      { id: "pm2-list", title: "PM2 List", tags: ["node", "pm2"], command: "pm2 ls || true" },
      { id: "pm2-logs", title: "PM2 Logs (last 100)", tags: ["node", "pm2"], command: "pm2 logs --lines 100 || true" },
    ],
  },
  {
    id: "docker",
    title: "Docker",
    icon: Boxes,
    description: "Common Docker and Compose actions.",
    tasks: [
      { id: "docker-version", title: "Docker: Version", tags: ["docker", "info"], command: "docker version || true" },
      { id: "docker-info", title: "Docker: Info", tags: ["docker", "info"], command: "docker info || true" },
      { id: "docker-df", title: "Docker: Disk usage", tags: ["docker", "info"], command: "docker system df || true" },
      { id: "docker-ps", title: "Docker: List containers", tags: ["docker", "info"], command: "docker ps -a" },
      { id: "docker-ps-running", title: "Docker: Running containers", tags: ["docker", "info"], command: "docker ps" },
      { id: "docker-images", title: "Docker: List images", tags: ["docker", "info"], command: "docker images" },
      { id: "docker-networks", title: "Docker: List networks", tags: ["docker", "info"], command: "docker network ls || true" },
      { id: "docker-volumes", title: "Docker: List volumes", tags: ["docker", "info"], command: "docker volume ls || true" },
      { id: "docker-stats", title: "Docker: Container stats", tags: ["docker", "info"], command: "docker stats --no-stream || true" },
      { id: "docker-events", title: "Docker: Events (stream)", tags: ["docker", "debug"], longRunning: true, command: "docker events" },

      { id: "compose-ps", title: "Compose: ps", tags: ["docker", "compose"], command: "docker compose ps || docker-compose ps || true" },
      { id: "compose-logs", title: "Compose: logs (tail)", tags: ["docker", "compose"], command: "docker compose logs --tail 200 || docker-compose logs --tail 200 || true" },
      { id: "compose-logs-follow", title: "Compose: logs (follow)", tags: ["docker", "compose"], longRunning: true, command: "docker compose logs -f --tail 200 || docker-compose logs -f --tail 200 || true" },
      { id: "compose-restart", title: "Compose: restart", tags: ["docker", "compose"], command: "docker compose restart || docker-compose restart || true" },

      {
        id: "docker-container-ps",
        title: "Container: Details",
        tags: ["docker", "container"],
        requires: ["container"],
        command: "docker ps -a --filter \"name={{container}}\"",
      },
      {
        id: "docker-container-status",
        title: "Container: Status (state/health)",
        tags: ["docker", "container", "info"],
        requires: ["container"],
        command:
          "docker inspect -f '{{.State.Status}} {{if .State.Health}}{{.State.Health.Status}}{{end}}' {{container}} 2>/dev/null || docker inspect -f '{{.State.Status}}' {{container}} 2>/dev/null || true",
      },
      {
        id: "docker-container-start",
        title: "Container: Start",
        tags: ["docker", "container"],
        requires: ["container"],
        command: "docker start {{container}}",
      },
      {
        id: "docker-container-stop",
        title: "Container: Stop",
        tags: ["docker", "container"],
        requires: ["container"],
        command: "docker stop {{container}}",
      },
      {
        id: "docker-container-restart",
        title: "Container: Restart",
        tags: ["docker", "container"],
        requires: ["container"],
        command: "docker restart {{container}}",
      },
      {
        id: "docker-container-logs-tail",
        title: "Container: Logs (tail 200)",
        tags: ["docker", "container", "logs"],
        requires: ["container"],
        command: "docker logs --tail 200 {{container}} || true",
      },
      {
        id: "docker-container-logs-follow",
        title: "Container: Logs (follow)",
        tags: ["docker", "container", "logs"],
        requires: ["container"],
        longRunning: true,
        command: "docker logs -f {{container}}",
      },
      {
        id: "docker-container-top",
        title: "Container: Processes (top)",
        tags: ["docker", "container", "info"],
        requires: ["container"],
        command: "docker top {{container}} || true",
      },
      {
        id: "docker-container-stats",
        title: "Container: Stats (no-stream)",
        tags: ["docker", "container", "info"],
        requires: ["container"],
        command: "docker stats --no-stream {{container}} || true",
      },
      {
        id: "docker-container-ports",
        title: "Container: Ports",
        tags: ["docker", "container", "info"],
        requires: ["container"],
        command: "docker port {{container}} || true",
      },
      {
        id: "docker-container-inspect",
        title: "Container: Inspect (summary)",
        tags: ["docker", "container", "info"],
        requires: ["container"],
        command: "docker inspect {{container}} | sed -n '1,120p'",
      },
      {
        id: "docker-container-env",
        title: "Container: Env (from inspect)",
        tags: ["docker", "container", "info"],
        requires: ["container"],
        command: "docker inspect -f '{{range .Config.Env}}{{println .}}{{end}}' {{container}} 2>/dev/null | sed -n '1,200p' || true",
      },
      {
        id: "docker-container-sh-check",
        title: "Container: Run a quick shell check",
        tags: ["docker", "container"],
        requires: ["container"],
        command: "docker exec {{container}} sh -lc 'whoami; pwd; ls -la | sed -n \"1,80p\"' 2>/dev/null || true",
      },
      {
        id: "docker-container-remove-force",
        title: "Container: Remove (force)",
        tags: ["docker", "container", "danger"],
        requires: ["container"],
        command: "docker rm -f {{container}}",
      },

      {
        id: "docker-image-pull",
        title: "Image: Pull",
        tags: ["docker", "image"],
        requires: ["image"],
        command: "docker pull {{image}}",
      },
      {
        id: "docker-image-inspect",
        title: "Image: Inspect (summary)",
        tags: ["docker", "image", "info"],
        requires: ["image"],
        command: "docker inspect {{image}} | sed -n '1,160p' || true",
      },
      {
        id: "docker-image-history",
        title: "Image: History",
        tags: ["docker", "image"],
        requires: ["image"],
        command: "docker history {{image}} || true",
      },
      {
        id: "docker-image-containers",
        title: "Image: Containers using this image",
        tags: ["docker", "image", "info"],
        requires: ["image"],
        command: "docker ps -a --filter ancestor={{image}} --format 'table {{.Names}}\\t{{.Status}}\\t{{.Image}}' || true",
      },
      {
        id: "docker-image-remove",
        title: "Image: Remove (rmi)",
        tags: ["docker", "image", "danger"],
        requires: ["image"],
        command: "docker rmi {{image}}",
      },
    ],
  },
  {
    id: "nginx",
    title: "Nginx",
    icon: Globe,
    description: "Install and troubleshoot Nginx.",
    tasks: [
      { id: "nginx-install", title: "Install Nginx", tags: ["nginx", "install"], command: "sudo apt-get update && sudo apt-get install -y nginx" },
      { id: "nginx-status", title: "Nginx Status", tags: ["nginx", "service"], command: "sudo systemctl status nginx --no-pager || true" },
      { id: "nginx-test", title: "Test Config", tags: ["nginx", "config"], command: "sudo nginx -t || true" },
      { id: "nginx-sites", title: "List Sites Enabled", tags: ["nginx", "config"], command: "ls -la /etc/nginx/sites-enabled || true" },
      { id: "nginx-sites-available", title: "List Sites Available", tags: ["nginx", "config"], command: "ls -la /etc/nginx/sites-available || true" },
      { id: "nginx-conf", title: "View nginx.conf", tags: ["nginx", "config"], command: "sudo sed -n '1,200p' /etc/nginx/nginx.conf || true" },
      { id: "nginx-reload", title: "Reload Nginx", tags: ["nginx", "service"], command: "sudo systemctl reload nginx || true" },
      { id: "nginx-restart", title: "Restart Nginx", tags: ["nginx", "service"], command: "sudo systemctl restart nginx || true" },
      { id: "nginx-logs", title: "Access/Error Logs (tail)", tags: ["nginx", "logs"], command: "sudo tail -n 120 /var/log/nginx/access.log /var/log/nginx/error.log 2>/dev/null || true" },
      { id: "nginx-error-follow", title: "Error log (follow)", tags: ["nginx", "logs"], longRunning: true, command: "sudo tail -f /var/log/nginx/error.log 2>/dev/null || true" },
      { id: "nginx-access-follow", title: "Access log (follow)", tags: ["nginx", "logs"], longRunning: true, command: "sudo tail -f /var/log/nginx/access.log 2>/dev/null || true" },
      { id: "nginx-listen", title: "Listening ports (nginx)", tags: ["nginx", "debug"], command: "sudo ss -ltnp | grep -i nginx || true" },
      {
        id: "nginx-site-view",
        title: "Enabled site: View config",
        tags: ["nginx", "config"],
        requires: ["nginx_site"],
        command: "sudo sed -n '1,200p' /etc/nginx/sites-enabled/{{nginx_site}} || true",
      },
      {
        id: "nginx-site-resolve",
        title: "Enabled site: Resolve symlink target",
        tags: ["nginx", "config"],
        requires: ["nginx_site"],
        command: "readlink -f /etc/nginx/sites-enabled/{{nginx_site}} || true",
      },
      {
        id: "nginx-site-view-resolved",
        title: "Enabled site: View resolved file",
        tags: ["nginx", "config"],
        requires: ["nginx_site"],
        command:
          "p=$(readlink -f /etc/nginx/sites-enabled/{{nginx_site}} 2>/dev/null) && [ -n \"$p\" ] && sudo sed -n '1,220p' \"$p\" || true",
      },
      {
        id: "nginx-site-grep",
        title: "Enabled site: Find server_name/listen",
        tags: ["nginx", "config"],
        requires: ["nginx_site"],
        command: "sudo grep -nE 'server_name|listen' /etc/nginx/sites-enabled/{{nginx_site}} || true",
      },
      {
        id: "nginx-site-disable",
        title: "Enabled site: Disable (remove symlink)",
        tags: ["nginx", "danger"],
        requires: ["nginx_site"],
        command: "sudo rm -f /etc/nginx/sites-enabled/{{nginx_site}} && echo 'disabled' || true",
      },
      {
        id: "nginx-site-disable-reload",
        title: "Enabled site: Disable + test + reload",
        tags: ["nginx", "danger"],
        requires: ["nginx_site"],
        command: "sudo rm -f /etc/nginx/sites-enabled/{{nginx_site}} && sudo nginx -t && sudo systemctl reload nginx || true",
      },
      {
        id: "nginx-available-view",
        title: "Available site: View config",
        tags: ["nginx", "config"],
        requires: ["nginx_site_available"],
        command: "sudo sed -n '1,220p' /etc/nginx/sites-available/{{nginx_site_available}} || true",
      },
      {
        id: "nginx-available-enable",
        title: "Available site: Enable (symlink)",
        tags: ["nginx", "danger"],
        requires: ["nginx_site_available"],
        command:
          "sudo ln -sfn /etc/nginx/sites-available/{{nginx_site_available}} /etc/nginx/sites-enabled/{{nginx_site_available}} && echo 'enabled' || true",
      },
      {
        id: "nginx-available-enable-reload",
        title: "Available site: Enable + test + reload",
        tags: ["nginx", "danger"],
        requires: ["nginx_site_available"],
        command:
          "sudo ln -sfn /etc/nginx/sites-available/{{nginx_site_available}} /etc/nginx/sites-enabled/{{nginx_site_available}} && sudo nginx -t && sudo systemctl reload nginx || true",
      },
      {
        id: "nginx-site-test-and-reload",
        title: "Test & reload (after edits)",
        tags: ["nginx", "service"],
        command: "sudo nginx -t && sudo systemctl reload nginx",
      },
    ],
  },
  {
    id: "databases",
    title: "Databases",
    icon: Database,
    description: "Postgres/MySQL quick checks.",
    tasks: [
      { id: "postgres-status", title: "Postgres Status", tags: ["postgres", "service"], command: "sudo systemctl status postgresql --no-pager || true" },
      { id: "postgres-conn", title: "Postgres: psql connect (local)", tags: ["postgres", "cli"], command: "psql -U postgres -c 'SELECT version();' || true" },
      { id: "mysql-status", title: "MySQL Status", tags: ["mysql", "service"], command: "sudo systemctl status mysql --no-pager || true" },
      { id: "mysql-version", title: "MySQL: version", tags: ["mysql", "cli"], command: "mysql --version || true" },
    ],
  },
  {
    id: "security",
    title: "Security",
    icon: Shield,
    description: "Basic security checks (read-only).",
    tasks: [
      { id: "ufw", title: "UFW Status", tags: ["security", "firewall"], command: "sudo ufw status verbose || true" },
      { id: "fail2ban", title: "Fail2ban Status", tags: ["security", "fail2ban"], command: "sudo fail2ban-client status || true" },
      { id: "sudoers", title: "Sudoers (who can sudo)", tags: ["security", "sudo"], command: "getent group sudo || getent group wheel || true" },
      { id: "lastlog", title: "Recent Logins", tags: ["security", "auth"], command: "last -n 30 || true" },
      { id: "ssh-keys", title: "Authorized Keys (current user)", tags: ["security", "ssh"], command: "ls -la ~/.ssh && sed -n '1,120p' ~/.ssh/authorized_keys 2>/dev/null || true" },
    ],
  },
  {
    id: "logs",
    title: "Logs",
    icon: FileText,
    description: "Quick log tails for common services.",
    tasks: [
      { id: "syslog", title: "syslog (tail)", tags: ["logs"], command: "sudo tail -n 200 /var/log/syslog 2>/dev/null || true" },
      { id: "messages", title: "messages (tail)", tags: ["logs"], command: "sudo tail -n 200 /var/log/messages 2>/dev/null || true" },
      { id: "journal-nginx", title: "journalctl nginx", tags: ["logs", "nginx"], command: "sudo journalctl -u nginx -n 200 --no-pager || true" },
      { id: "journal-docker", title: "journalctl docker", tags: ["logs", "docker"], command: "sudo journalctl -u docker -n 200 --no-pager || true" },
    ],
  },
  {
    id: "git",
    title: "Git",
    icon: Layers,
    description: "Common git operations (read-only / safe).",
    tasks: [
      { id: "git-version", title: "Git Version", tags: ["git", "info"], command: "git --version || true" },
      { id: "git-status", title: "git status", tags: ["git", "repo"], command: "git status || true" },
      { id: "git-branches", title: "Branches", tags: ["git", "repo"], command: "git branch -av || true" },
      { id: "git-log", title: "Recent Commits", tags: ["git", "repo"], command: "git --no-pager log --oneline -n 20 || true" },
      { id: "git-remote", title: "Remotes", tags: ["git", "repo"], command: "git remote -v || true" },
    ],
  },
  {
    id: "performance",
    title: "Performance",
    icon: Flame,
    description: "Quick performance triage commands.",
    tasks: [
      { id: "top-cpu", title: "Top CPU", tags: ["perf"], command: "ps aux --sort=-%cpu | head -n 20" },
      { id: "top-mem", title: "Top Memory", tags: ["perf"], command: "ps aux --sort=-%mem | head -n 20" },
      { id: "iostat", title: "IOStat (if available)", tags: ["perf", "disk"], command: "iostat -xz 1 3 || true" },
      { id: "vmstat", title: "vmstat", tags: ["perf"], command: "vmstat 1 5 || true" },
      { id: "netstat", title: "Connections (summary)", tags: ["perf", "network"], command: "ss -s || netstat -s || true" },
    ],
  },
  {
    id: "keys-ssl",
    title: "Keys & TLS",
    icon: KeyRound,
    description: "TLS and key checks (read-only).",
    tasks: [
      { id: "openssl-version", title: "OpenSSL Version", tags: ["tls", "info"], command: "openssl version -a || true" },
      { id: "cert-expiry", title: "Cert Expiry (domain)", tags: ["tls", "debug"], command: "echo | openssl s_client -servername example.com -connect example.com:443 2>/dev/null | openssl x509 -noout -dates || true" },
      { id: "letsencrypt", title: "Certbot Certificates", tags: ["tls", "letsencrypt"], command: "sudo certbot certificates 2>/dev/null || true" },
    ],
  },
];

export function getDefaultGroupId() {
  return TASK_GROUPS[0]?.id || "system-info";
}

export function findGroupById(id) {
  return TASK_GROUPS.find((g) => g.id === id) || null;
}
